name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.X]

    steps:
      - uses: actions/checkout@v2
      - name: Starrting Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v1
        with:
          node-version: ${{matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build
      - name: linting Typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:css
      - name: unit testing
        run: npm run test:unit